export const levels = [
  {
    id: 'resident',
    label: 'Rezidentų triukas',
    description: 'Direktorius dažnai nusisuka. Laikas 90 s, rizika minimali.',
    timeLimit: 90,
    suspicionMax: 100,
    suspicionIncrease: 32,
    suspicionDecay: 26,
    playerSpeed: 180,
    spawnInterval: 1.2,
    tokenValue: [600, 1200],
    lookDuration: [1.6, 2.6],
    distractDuration: [1.8, 3.2],
    maxTokens: 8,
  },
  {
    id: 'chief',
    label: 'Skyriaus vadovė',
    description: 'Direktorius akylas, bet dar pavyksta suktis. Laikas 75 s.',
    timeLimit: 75,
    suspicionMax: 100,
    suspicionIncrease: 42,
    suspicionDecay: 20,
    playerSpeed: 190,
    spawnInterval: 1.05,
    tokenValue: [750, 1500],
    lookDuration: [1.4, 2.2],
    distractDuration: [1.6, 2.8],
    maxTokens: 9,
  },
  {
    id: 'board',
    label: 'Valdybos posėdis',
    description: 'Visi žvilgsniai į tave. Laikas 60 s, bet grantai vertesni.',
    timeLimit: 60,
    suspicionMax: 100,
    suspicionIncrease: 52,
    suspicionDecay: 18,
    playerSpeed: 200,
    spawnInterval: 0.9,
    tokenValue: [900, 1800],
    lookDuration: [1.2, 2.0],
    distractDuration: [1.4, 2.4],
    maxTokens: 10,
  },
];

export default levels;
